# Generated by Django 5.0.3 on 2024-04-07 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_whishlist_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('DELL', 'DELL'), ('LENOVO', 'LENOVO'), ('HP', 'HP'), ('ASUS', 'ASUS'), ('MSI', 'MSI'), ('MACBOOK', 'MACBOOK')], max_length=10),
        ),
    ]
